VERSION 0.6

deps:
    FROM golang:1.18-alpine
    WORKDIR /pkg/transfer
    COPY go.mod go.sum ./
    RUN go mod download

artifact:
    FROM +deps
    COPY . .
    SAVE ARTIFACT .

unit-test:
    FROM +artifact
    COPY gcp_test.go .
    RUN go test