version: '3'
services:
  channel_1:
    image: digitaltv-recorder:latest
    container_name: channel_1
    restart: always
    stop_signal: SIGINT
    env_file:
      - ./deploy.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - ~/Documents/gcp_access/medialab-01.json:/app/config/gcp.json:ro
      - ~/Videos:/app/recording:rw
      #- recording:/app/recording:rw
    devices:
      - /dev/dri:/dev/dri 
      - /dev/dvb:/dev/dvb
    networks:
      vpcgst: {}

volumes:
  recording: {}
      
networks:
  vpcgst:
    name: gst-network
    driver: bridge
    driver_opts:
        com.docker.network.bridge.name: br_gst